name: bili-auto on:
workflow_dispatch: {} schedule:
- cron: '0 */6 ***' # 每6小时跑一次(UTC)
permissions: contents: write
jobs: run:
runs-on: ubuntu-latest steps:
- uses: actions/checkout@v4 with:
fetch-depth: 0  
- uses: actions/setup-node@v4
    with:
      node-version: '20'

  - name: Install Playwright
    run: |
      npm init -y
      npm i playwright@^1.46.0
      npx playwright install --with-deps chromium

  - name: Run scraper (inline)
    env:
      KEYWORDS: 詹姆斯中国行,湖人,科比   # ← 修改你的关键词（逗号分隔）
    run: |
      node - <<'NODE'
      const { chromium } = require('playwright');
      const fs = require('fs'), path = require('path');
      const kw = (process.env.KEYWORDS||'詹姆斯中国行').split(',').map(s=>s.trim()).filter(Boolean);
      const ts = ()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`};
      const slug=s=>s.replace(/[^\w\u4e00-\u9fa5]+/g,'-').replace(/-+/g,'-');
      (async ()=>{
        const browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
        fs.mkdirSync('data',{recursive:true});fs.mkdirSync('screenshots',{recursive:true});
        for(const k of kw){
          const ctx=await browser.newContext({locale:'zh-CN',timezoneId:'Asia/Shanghai',viewport:{width:1366,height:900}});
          const page=await ctx.newPage();
          await page.addInitScript(()=>{Object.defineProperty(navigator,'webdriver',{get:()=>undefined});});
          const url=`https://search.bilibili.com/all?keyword=${encodeURIComponent(k)}&from_source=webtop_search&order=totalrank`;
          console.log('open',url);
          await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});
          await page.waitForTimeout(1500);
          for(let i=0;i<2;i++){await page.mouse.wheel(0,900);await page.waitForTimeout(1200);}
          await page.screenshot({path:path.join('screenshots',`${slug(k)}_${ts()}.png`),fullPage:true});
          let cards=await page.$$('div.bili-video-card');
          if(cards.length===0){cards=await page.$$('div.video-list div.bili-video-card');}
          const items=[];
          for(const c of cards.slice(0,40)){
            try{
              const titleEl=await c.$('h3.bili-video-card__info--tit');
              const a=await c.$('a'); const upEl=await c.$('.bili-video-card__info--author');
              const stats=await c.$$('.bili-video-card__stats--item');
              const title=titleEl? (await titleEl.getAttribute('title')) || (await titleEl.innerText()||'').trim() : '';
              let link=a? (await a.getAttribute('href'))||'' : ''; if(link.startsWith('//')) link='https:'+link;
              const views=stats[0]? (await stats[0].innerText()||'').trim():'N/A';
              const danmaku=stats[1]? (await stats[1].innerText()||'').trim():'N/A';
              const up=upEl? (await upEl.innerText()||'').trim():'';
              if(title&&link) items.push({title,views,danmaku,up_name:up,link});
            }catch(e){}
          }
          const file=path.join('data',`${slug(k)}_${ts()}.json`);
          fs.writeFileSync(file,JSON.stringify({keyword:k,count:items.length,items},null,2),'utf-8');
          await ctx.close();
        }
        await browser.close();
      })();
      NODE

  - name: Commit results
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      git add data/ screenshots/ || true
      git commit -m "data: update $(date -u +'%F %T')" || echo "no changes"
      git push
